name: Build Static ARMv7 Router
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Toolchain and Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libpcap-dev

    - name: Compile Reaver Pure Static
      run: |
        cd src
        ./configure
        make

    - name: Save Artifact
      uses: actions/upload-artifact@v4
      with:
        name: reaver-static-armv7
        path: src/reaver
